### ISSUE TITLE
Roubando scripts? Cadê os créditos?

### ISSUE THREAD

**Issue by DarkMod3** [DiversasVariedades/Hacks-Plataformas#1]
"Então, estou vendo que você está roubando os scripts e colocando no seu GitHub como se fossem seus. E, para piorar, ainda está postando vídeos no seu canal do YouTube com encurtadores para ganhar alguns centavos? Fica tranquilo, porque em poucos dias os vídeos já vão cair com os strikes.

GitHub com créditos: https://github.com/DarkMod3/CMSP-Plataformas-Hacks

**Comment by DiversasVariedades** [comment]
"Boa noite, os créditos ainda estão nos scripts, eu postei um vídeo com o
script do "marcospc10" e falei dele no vídeo, você assistiu o vídeo
completo?"

Em qua., 16 de out. de 2024, 23:19, DarkMode ***@***.***>
escreveu:

**Comment by DiversasVariedades** [comment]
"Não fiz os vídeos com intenção de roubar os scripts, apenas compartilhar
eles, eu te mandarei o link do vídeo e o minuto que eu eu falo que os
créditos são de "marcospc10". Inclusive, se você olhar na página do Github,
terá uma parte que está escrito "Créditos nos códigos"

Em qua., 16 de out. de 2024, 23:21, Kevyn Do Nascimento <
***@***.***> escreveu:

**Comment by DarkMod3** [comment]
Eu entendi a parte de divulgar e compartilhar os videos só que ta vindo pessoas reclamar por conta que você coloca os encurtados e no github só entrando dentro dos script que da pra ver os creditos

**Comment by DarkMod3** [comment]
Mas tranquilo só coloca os creditos no readme do github pra ficar mais facil e os encurtadores e por sua conta mesmo

**Comment by DiversasVariedades** [comment]
https://youtu.be/mEKWA3nRGKM?si=_KE3cCJjQlHxQnc7

Minuto: 3:16

Em qua., 16 de out. de 2024, 23:19, DarkMode ***@***.***>
escreveu:

**Comment by DiversasVariedades** [comment]
Entendo amigo, deixa eu te perguntar, você tem whatsapp? Gostaria de
conversar por lá?

(13) 99747-8456

Em qua., 16 de out. de 2024, 23:27, DarkMode ***@***.***>
escreveu:

**Comment by DiversasVariedades** [comment]
Perfeito, não queria arrumar nenhum tipo de problema pra mim, nem pra
ninguém entende, estou na luta tentando arranjar conteúdo para o canal, mas
pode ficar tranquilo, garantirei que os créditos vão estar mais visíveis.

Em qua., 16 de out. de 2024, 23:27, DarkMode ***@***.***>
escreveu:
